# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wistia < Formula
  desc "Data API: Wistia Data API"
  homepage "https://github.com/wistia/wistia-cli"
  version "2026.03.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.03.9/homebrew-wistia-cli_Darwin_x86_64.tar.gz"
      sha256 "7bbdd773eae0dc74d128ac024305cdc4297838da43d0d3d410e8daa58733f141"

      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.03.9/homebrew-wistia-cli_Darwin_arm64.tar.gz"
      sha256 "9c47998d358c54b398c38d9235887425cf0446d4f085ff2008eba55a2463cc05"

      define_method(:install) do
        bin.install "wistia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.03.9/homebrew-wistia-cli_Linux_x86_64.tar.gz"
      sha256 "b1893581232d8535d6304739e31bf0c6a712534451d663554e4fc97ddd227762"
      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.03.9/homebrew-wistia-cli_Linux_arm64.tar.gz"
      sha256 "e2ab9814df29d7a2a8738b29d41cff002318adba18f2fc744c79b104ac49f73d"
      define_method(:install) do
        bin.install "wistia"
      end
    end
  end
end
