# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wistia < Formula
  desc "Data API: Wistia Data API"
  homepage "https://github.com/wistia/wistia-cli"
  version "2026.03.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.03.6/wistia-cli_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "eab98e63c569fa8e701393c9b2096bd931751e3f65c963edb49d57a79822344b"

      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.03.6/wistia-cli_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "baa1fb233adfa57410cf5210a6dbb3699d3352c00a88187541afc6450e2c3259"

      define_method(:install) do
        bin.install "wistia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.03.6/wistia-cli_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "31bbfd2ad2291c2374c8a5c453d0c2725084dbb4daf00b27f1baef99fe471ce4"
      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.03.6/wistia-cli_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "11fa49cd176c21b98f014446fb2e0d232adb9fef47f8088150c05a03b397bb78"
      define_method(:install) do
        bin.install "wistia"
      end
    end
  end
end
