# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wistia < Formula
  desc "Data API: Wistia Data API"
  homepage "https://github.com/wistia/wistia-cli"
  version "2026.03.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.03.5/wistia-cli_Darwin_x86_64.tar.gz"
      sha256 "a2d3fc62c8dd30b61b56e057ed459c306297f9b802500a23e067d65aed1e63cb"

      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.03.5/wistia-cli_Darwin_arm64.tar.gz"
      sha256 "128e807c7c4df653fbd9dd33d4e1379355dbafb9bf78fd7e5943e529274ad3b1"

      define_method(:install) do
        bin.install "wistia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.03.5/wistia-cli_Linux_x86_64.tar.gz"
      sha256 "d3bcaee831b07ebcbf6e033474e8bc2473b64039e8a977a29ec065d2eb183be3"
      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.03.5/wistia-cli_Linux_arm64.tar.gz"
      sha256 "ca2d306b11dea2dc603ccbc57fd5c3b4bf73f53c19a7060e54f4e7f0ee28dc00"
      define_method(:install) do
        bin.install "wistia"
      end
    end
  end
end
