# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WistiaCli < Formula
  desc "Data API: Wistia Data API"
  homepage "https://github.com/wistia/wistia-cli"
  version "2026.03.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.03.10/homebrew-wistia-cli_Darwin_x86_64.tar.gz"
      sha256 "b70a53e349c52a82f56f58269da24904eb886ca21139218a6f0bd099986f7c7e"

      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.03.10/homebrew-wistia-cli_Darwin_arm64.tar.gz"
      sha256 "0b8f24ee559945061d598bd8bcb2eb1e5eb14ac138fa52a60220705a5f713001"

      define_method(:install) do
        bin.install "wistia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.03.10/homebrew-wistia-cli_Linux_x86_64.tar.gz"
      sha256 "00b1f645d3681c96f9c173503b8096501f0d4a5f025b622d1a908cac56cd1266"
      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.03.10/homebrew-wistia-cli_Linux_arm64.tar.gz"
      sha256 "ab8d30c4f1c056c2e8731fb85eeecb540d885b1dd772ea4e09eda2a0da412e19"
      define_method(:install) do
        bin.install "wistia"
      end
    end
  end
end
