# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WistiaCli < Formula
  desc "Data API: Wistia Data API"
  homepage "https://github.com/wistia/wistia-cli"
  version "2026.04.01"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.04.01/homebrew-wistia-cli_Darwin_x86_64.tar.gz"
      sha256 "d84bd586b1b93da3c85c13d02ccb03a421103d8f26f009c9a1ba8d4b42d216e4"

      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.04.01/homebrew-wistia-cli_Darwin_arm64.tar.gz"
      sha256 "bd5d05bd4b9a1e3d4a78603fdd3e320f5f2b69fc6913af4d739d6074864a6a0d"

      define_method(:install) do
        bin.install "wistia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.04.01/homebrew-wistia-cli_Linux_x86_64.tar.gz"
      sha256 "0a646bc961fe631b97162b27d2e50b9a8d4eb3f5b6cbbd792da0d2eef0a0e91f"
      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/homebrew-wistia-cli/releases/download/v2026.04.01/homebrew-wistia-cli_Linux_arm64.tar.gz"
      sha256 "65733678edc40f9c207fa979bea261ca646dbf5358c0665695b8b73581a0506b"
      define_method(:install) do
        bin.install "wistia"
      end
    end
  end
end
